name: prettier/lint Test
on:
  push:
    branches-ignore:
      - main
      - development
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.SUB_MODULE_TOKEN }}
          submodules: true

      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.1
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile

      - name: cache-node-modules
        uses: actions/cache@v3
        id: node_modules_cache_id
        env:
          cache-name: cache-node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}


      - name: format-check
        run: pnpm run check
      - name: lint-check
        run: pnpm run lint
